# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x05todos\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x01\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x11\n\x0fGetTodosRequest\".\n\x10GetTodosResponse\x12\x1a\n\x05todos\x18\x01 \x03(\x0b\x32\x0b.todos.Todo\" \n\x12GetTodoByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x13GetTodoByIdResponse\x12\x19\n\x04todo\x18\x01 \x01(\x0b\x32\x0b.todos.Todo\".\n\x11\x43reateTodoRequest\x12\x19\n\x04todo\x18\x01 \x01(\x0b\x32\x0b.todos.Todo\"/\n\x12\x43reateTodoResponse\x12\x19\n\x04todo\x18\x01 \x01(\x0b\x32\x0b.todos.Todo\".\n\x11UpdateTodoRequest\x12\x19\n\x04todo\x18\x01 \x01(\x0b\x32\x0b.todos.Todo\"/\n\x12UpdateTodoResponse\x12\x19\n\x04todo\x18\x01 \x01(\x0b\x32\x0b.todos.Todo\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x12\x44\x65leteTodoResponse\x12\x19\n\x04todo\x18\x01 \x01(\x0b\x32\x0b.todos.Todo2\xe3\x02\n\x0bTodoService\x12=\n\x08GetTodos\x12\x16.todos.GetTodosRequest\x1a\x17.todos.GetTodosResponse\"\x00\x12\x46\n\x0bGetTodoById\x12\x19.todos.GetTodoByIdRequest\x1a\x1a.todos.GetTodoByIdResponse\"\x00\x12\x43\n\nCreateTodo\x12\x18.todos.CreateTodoRequest\x1a\x19.todos.CreateTodoResponse\"\x00\x12\x43\n\nUpdateTodo\x12\x18.todos.UpdateTodoRequest\x1a\x19.todos.UpdateTodoResponse\"\x00\x12\x43\n\nDeleteTodo\x12\x18.todos.DeleteTodoRequest\x1a\x19.todos.DeleteTodoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODO']._serialized_start=55
  _globals['_TODO']._serialized_end=205
  _globals['_GETTODOSREQUEST']._serialized_start=207
  _globals['_GETTODOSREQUEST']._serialized_end=224
  _globals['_GETTODOSRESPONSE']._serialized_start=226
  _globals['_GETTODOSRESPONSE']._serialized_end=272
  _globals['_GETTODOBYIDREQUEST']._serialized_start=274
  _globals['_GETTODOBYIDREQUEST']._serialized_end=306
  _globals['_GETTODOBYIDRESPONSE']._serialized_start=308
  _globals['_GETTODOBYIDRESPONSE']._serialized_end=356
  _globals['_CREATETODOREQUEST']._serialized_start=358
  _globals['_CREATETODOREQUEST']._serialized_end=404
  _globals['_CREATETODORESPONSE']._serialized_start=406
  _globals['_CREATETODORESPONSE']._serialized_end=453
  _globals['_UPDATETODOREQUEST']._serialized_start=455
  _globals['_UPDATETODOREQUEST']._serialized_end=501
  _globals['_UPDATETODORESPONSE']._serialized_start=503
  _globals['_UPDATETODORESPONSE']._serialized_end=550
  _globals['_DELETETODOREQUEST']._serialized_start=552
  _globals['_DELETETODOREQUEST']._serialized_end=583
  _globals['_DELETETODORESPONSE']._serialized_start=585
  _globals['_DELETETODORESPONSE']._serialized_end=632
  _globals['_TODOSERVICE']._serialized_start=635
  _globals['_TODOSERVICE']._serialized_end=990
# @@protoc_insertion_point(module_scope)
